<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php _b('List of top searched terms'); ?></h3>
    <?php if ($config['save_log']) { ?>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _b('ID'); ?></th>
                <th><?php _b('Term'); ?></th>
                <th><?php _b('Weight'); ?></th>
            </tr>
            <?php foreach ($list as $dictionary) { ?>
                <tr>
                    <td><?php echo $this->escape($dictionary['id']); ?></td>
                    <td><?php echo $this->escape($dictionary['term']); ?></td>
                    <td><?php echo $this->escape($dictionary['weight']); ?></td>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _b('Save log option for search module not active'); ?>
        </div>
    <?php } ?>
</div>