<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="mt-3 mb-3">
        <h1><?php _e('List of top searched terms'); ?></h1>
    </div>
    <?php if ($config['save_log']) { ?>
        <table class="table table-striped table-bordered table-hover table-sm mt-3 mb-3">
            <tr>
                <th><?php _e('Term'); ?></th>
                <th><?php _e('Count of search'); ?></th>
            </tr>
            <?php foreach ($list as $dictionary) { ?>
                <tr>
                    <td><?php echo $this->escape($dictionary['term']); ?></td>
                    <td><?php echo $this->escape($dictionary['weight']); ?></td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-danger mt-3 mb-3" role="alert">
            <?php _e('Save log option for search module not active'); ?>
        </div>
    <?php } ?>
</div>