<div class="search-block">
    <?php if ($block['options']['type'] == 'ajax') { ?>
        <?php if ($block['options']['block-effect']) {
            $script = <<<'EOT'
(function($){
    var length = %s;
    var timer = null;
    function search() {
        var keyword = $("#search-keyword").val();
        if (keyword.length >= length) {
            $.get("%s", {q: keyword}).done(function (data) {
                $('.search-results').html('');
                var results = jQuery.parseJSON(data);
                $(results).each(function (key, value) {
                    if (value.image != '') {
                        $('.search-results').append('<a class="dropdown-item ' + value.class + '" title="' + value.title + '" href="' + value.url + '"><img src="' + value.image + '" alt="' + value.title + '"> ' + value.title + '</a>');
                    } else {
                        $('.search-results').append('<a class="dropdown-item ' + value.class + '" title="' + value.title + '" href="' + value.url + '">' + value.title + '</a>');
                    }
                })
            });
        } else {
            $('.search-results').html('');
        }
    }
    $("#search-keyword").keyup(function() {
        clearTimeout(timer);
        timer = setTimeout(search, %s);
    }).blur(function () {
        $(".search-results").fadeOut(%s);
    }).focus(function () {
        var keyword = $("#search-keyword").val();
        $(".search-info-text").remove();
        if (keyword.length == 0) {
            $(".search-results").show().append('<a class="dropdown-item search-info-text">%s</a>');
        } else {
            $(".search-results").show().append('<a class="dropdown-item search-info-text">%s</a>');
        }
    });
})(jQuery)
EOT;
            $script = sprintf(
                $script,
                $block['length'],
                $block['ajax'],
                $block['options']['delay'],
                $block['options']['delay'],
                _b('Please input term for search'),
                _b('Searching, please wait ...')
            );
            $this->jQuery();
            $this->footScript()->appendScript($script);
            $this->css($this->assetModule('front/block.css', 'search'));
        } ?>
        <div class="form-group">
            <form method="get" action="<?php echo $block['action']; ?>" <?php if (!empty($block['options']['target'])) {
                echo ' target="' . $block['options']['target'] . '"';
            } ?>>
                <div class="input-group">
                    <input id="search-keyword" type="text" class="form-control" name="q"
                           placeholder="<?php echo $block['options']['descriptiontitle']; ?>" autocomplete="off">
                    <?php if (!empty($block['options']['disable_submit_btn']) && $block['options']['disable_submit_btn']) { ?>
                        <div class="input-group-addon">
                            <i class="fa fa-search"></i>
                        </div>
                    <?php } else { ?>
                        <div class="input-group-btn">
                            <button class="btn btn-secondary">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    <?php } ?>
                </div>
            </form>
            <div class="search-results dropdown-menu"></div>
        </div>
    <?php } else { ?>
        <form method="get" action="<?php echo $block['action']; ?>"
            <?php if (!empty($block['options']['target'])) {
                echo ' target="' . $block['options']['target'] . '"';
            } ?>>
            <div class="input-group">
                <input type="text" class="form-control" name="q" placeholder="<?php echo _b('Search'); ?>">
                <div class="input-group-btn">
                    <?php if (!empty($block['list'])) { ?>
                        <a class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-search"></i>

                        </a>
                        <div class="dropdown-menu pull-right" id="js-search-menu">
                            <?php foreach ($block['list'] as $name => $label) { ?>
                                    <a class="dropdown-item" href="#" data-value="<?php echo $this->escape($name); ?>">
                                        <?php echo $this->escape($label); ?>
                                    </a>
                            <?php } ?>
                        </div>
                        <input type="hidden" name="m">
                    <?php } else { ?>
                        <?php if ($block['options']['module'] != 'all') { ?>
                            <input type="hidden" name="m" value="<?php echo $block['options']['module']; ?>">
                        <?php } ?>
                        <?php if (!empty($block['options']['disable_submit_btn']) && $block['options']['disable_submit_btn']) { ?>
                            <div class="input-group-addon">
                                <i class="fa fa-search"></i>
                            </div>
                        <?php } else { ?>
                            <button class="btn btn-secondary">
                                <i class="fa fa-search"></i>
                            </button>
                        <?php } ?>
                    <?php } ?>
                </div>
            </div>
        </form>
        <?php if (!empty($block['list']) && $block['options']['block-effect']) {
            $script = <<<'EOT'
$('#js-search-menu').on('click', 'a', function(e) {
    var $this = $(this);
    var val = $this.data('value');
    var form = $this.parents('form');
    var m = form.find('[name=m]');
    e.preventDefault();
    m.val(val);
    form[0].submit();
});
EOT;
            $this->footScript()->appendScript($script);
        } ?>
    <?php } ?>
</div>