<?php $this->footScript()->appendFile($this->assetModule('front/search-tabs.js')); ?>
<div class="row">
    <div class="col-lg-8 col-md-8 col-12 offset-lg-2 offset-md-2 mt-3 mb-3">
        <form method="get" id="js-search-form"
              data-url="<?php echo $this->url('search'); ?>"
              data-module-url="<?php echo $this->url('search', ['m' => '_NAME']); ?>"
              data-service-url="<?php echo $this->url('search', ['service' => '_NAME']); ?>"
              data-module="<?php echo $searchModule; ?>">
            <div class="search-tabs">
                <ul class="nav justify-content-center">
                    <li class="nav-item">
                        <a href="#" class="js-search-global nav-link<?php if (!$searchModule) {
                            echo ' active';
                        } ?>">
                            <?php _e('Global'); ?>
                        </a>
                    </li>
                    <?php foreach ($modules as $name => $data) {
                        echo sprintf(
                            '<li class="nav-item"><a data-name="%s" href="#" class="js-search-module nav-link%s">%s</a></li>',
                            $name,
                            $name == $searchModule ? ' active' : '',
                            $this->escape($data['title'])
                        );
                    } ?>
                </ul>
            </div>
            <div class="input-group">
                <input type="text" name="q" class="form-control" value="<?php echo $this->escape($query); ?>" placeholder="<?php _e('Keywords'); ?>">
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-primary">
                        <span class="fa fa-search"></span> <?php _e('Search'); ?>
                    </button>
                </div>
            </div>
            <div class="search-service">
                <ul class="nav justify-content-center">
                    <?php foreach ($service as $name => $data) {
                        echo sprintf(
                            '<li class="nav-item"><a data-name="%s" href="#" class="js-search-service nav-link">%s</a></li>',
                            $name,
                            $this->escape($data['title'])
                        );
                    } ?>
                </ul>
            </div>
        </form>
    </div>
</div>