<?php $this->footScript()->appendFile($this->assetModule('front/search-tabs.js')); ?>
<div class="row">
    <div class="col-md-8 col-md-offset-2 col-xs-12">
        <form method="get" id="js-search-form"
              data-url="<?php echo $this->url('search'); ?>"
              data-module-url="<?php echo $this->url('search', array('m' => '_NAME')); ?>"
              data-service-url="<?php echo $this->url('search', array('service' => '_NAME')); ?>"
              data-module="<?php echo $searchModule; ?>">
            <div class="search-tabs">
                <ul class="list-inline">
                    <li>
                        <a href="#" class="js-search-global<?php if (!$searchModule) {
                            echo ' active';
                        } ?>">
                            <?php _e('Global'); ?>
                        </a>
                    </li>
                    <?php foreach ($modules as $name => $data) {
                        echo sprintf(
                            '<li><a data-name="%s" href="#" class="js-search-module%s">%s</a></li>',
                            $name,
                            $name == $searchModule ? ' active' : '',
                            $this->escape($data['title'])
                        );
                    } ?>
                </ul>
            </div>
            <div class="input-group">
                <input type="text" name="q" class="form-control"
                       value="<?php echo $this->escape($query); ?>"
                       placeholder="<?php _e('Keywords'); ?>">
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-primary">
                        <span class="fa fa-search"></span> <?php _e('Search'); ?>
                    </button>
                </div>
            </div>
            <div class="search-service">
                <ul class="list-inline">
                    <?php foreach ($service as $name => $data) {
                        echo sprintf(
                            '<li><a data-name="%s" href="#" class="js-search-service">%s</a></li>',
                            $name,
                            $this->escape($data['title'])
                        );
                    } ?>
                </ul>
            </div>
        </form>
    </div>
</div>